import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import type { OfficialSource, PriceRow, WeeklyHours } from "../lib/place-record";

export const places = sqliteTable("places", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  branchName: text("branch_name").notNull().default(""),
  category: text("category").notNull().default("체험"),
  fullAddress: text("full_address").notNull().default(""),
  addressKey: text("address_key").notNull().default(""),
  province: text("province").notNull().default(""),
  city: text("city").notNull().default(""),
  district: text("district").notNull().default(""),
  weeklyHours: text("weekly_hours", { mode: "json" }).$type<WeeklyHours>().notNull(),
  holidayHours: text("holiday_hours").notNull().default("확인 필요"),
  reservationRequired: integer("reservation_required", { mode: "boolean" }).notNull().default(false),
  reservationOpenRule: text("reservation_open_rule").notNull().default(""),
  reservationUrl: text("reservation_url").notNull().default(""),
  ageRestriction: text("age_restriction").notNull().default("없음"),
  prices: text("prices", { mode: "json" }).$type<PriceRow[]>().notNull(),
  timeSurcharge: text("time_surcharge").notNull().default(""),
  themes: text("themes", { mode: "json" }).$type<string[]>().notNull(),
  environment: text("environment").notNull().default("혼합"),
  parkingType: text("parking_type").notNull().default("확인 필요"),
  parkingFee: text("parking_fee").notNull().default(""),
  parkingSupport: text("parking_support").notNull().default(""),
  nursingRoom: text("nursing_room").notNull().default("확인 필요"),
  changingTable: text("changing_table").notNull().default("확인 필요"),
  officialSources: text("official_sources", { mode: "json" }).$type<OfficialSource[]>().notNull(),
  imageUrl: text("image_url").notNull().default(""),
  imageSourceUrl: text("image_source_url").notNull().default(""),
  summary: text("summary").notNull().default(""),
  reasons: text("reasons", { mode: "json" }).$type<string[]>().notNull(),
  caution: text("caution").notNull().default(""),
  ageHint: text("age_hint").notNull().default("영유아부터"),
  score: integer("score").notNull().default(80),
  ticketCandidate: integer("ticket_candidate", { mode: "boolean" }).notNull().default(false),
  affiliateUrl: text("affiliate_url").notNull().default(""),
  status: text("status").notNull().default("pending"),
  duplicateOfId: integer("duplicate_of_id"),
  reviewer: text("reviewer").notNull().default(""),
  aiResearched: integer("ai_researched", { mode: "boolean" }).notNull().default(false),
  lastVerifiedAt: text("last_verified_at").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  index("idx_places_status").on(table.status),
  index("idx_places_address_key").on(table.addressKey),
  index("idx_places_region").on(table.province, table.city, table.district),
]);

export const researchRuns = sqliteTable("research_runs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  query: text("query").notNull(),
  status: text("status").notNull(),
  errorMessage: text("error_message").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
